/**
 * 
 */
package com.gs.oracle.command;

/**
 * @author Green Moon
 *
 */
public interface GuiCommandConstants {
	String _ACT_CMD = "";
	
	
	// connection dialog action commands
	String NEW_CONNECTION_ACT_CMD = "NEW_CONNECTION_ACT_CMD";
	String SAVE_CONNECTION_ACT_CMD = "SAVE_CONNECTION_ACT_CMD";
	String DELETE_CONNECTION_ACT_CMD = "DELETE_CONNECTION_ACT_CMD";
	String EDIT_CONNECTION_ACT_CMD = "EDIT_CONNECTION_ACT_CMD";
	String CANCEL_CONNECTION_ACT_CMD = "CANCEL_CONNECTION_ACT_CMD";
	String CONNECT_TO_DB_ACT_CMD = "CONNECT_TO_DB_ACT_CMD";
	String TEST_CONNECTION_ACT_CMD = "TEST_CONNECTION_ACT_CMD";
	
	String DB_SYNC_ACT_CMD = "DB_SYNC_ACT_CMD";
	String EXECUITE_CURRENT_SQL_ACT_CMD = "EXECUITE_CURRENT_SQL_ACT_CMD";
	String REFRESH_DATABASE_ACT_CMD = "REFRESH_DATABASE_ACT_CMD";
	String BACKUP_DATABSE_ACT_CMD = "BACKUP_DATABSE_ACT_CMD";
	
	
}
