/**
 * 
 */
package com.gs.oracle.command;

/**
 * @author Green Moon
 *
 */
public interface GuiCommandConstants {
	String _ACT_CMD = "";
	
	
	String NEW_CONNECTION_ACT_CMD 		= "NEW_CONNECTION_ACT_CMD";
	String NEW_CONN_W_CURR_ACT_CMD 		= "NEW_CONN_W_CURR_ACT_CMD";
	String DISCONN_DB__ACT_CMD 			= "DISCONN_DB__ACT_CMD";
	String DISCONN_ALL_DB__ACT_CMD 		= "DISCONN_ALL_DB__ACT_CMD";
	String NEW_QUERY_TAB_ACT_CMD 		= "NEW_QUERY_TAB_ACT_CMD";
	String OPEN_QUERY_FILE_ACT_CMD 		= "OPEN_QUERY_FILE_ACT_CMD";
	String SAVE_QUERY_FILE_ACT_CMD 		= "SAVE_QUERY_FILE_ACT_CMD";
	String SAVE_AS_QUERY_FILE_ACT_CMD 	= "SAVE_AS_QUERY_FILE_ACT_CMD";
	String NEW_QUERY_BUILDER_ACT_CMD 	= "NEW_QUERY_BUILDER_ACT_CMD";
	String NEW_SCHEMA_DESIGNER_ACT_CMD 	= "NEW_SCHEMA_DESIGNER_ACT_CMD";
	String OPEN_RECENT_SQL_FILE_ACT_CMD = "OPEN_RECENT_SQL_FILE_ACT_CMD";
	String OPEN_RECENT_SCHEMA_D_ACT_CMD = "OPEN_RECENT_SCHEMA_D_ACT_CMD";
	
	String SAVE_CONNECTION_ACT_CMD 		= "SAVE_CONNECTION_ACT_CMD";
	String DELETE_CONNECTION_ACT_CMD 	= "DELETE_CONNECTION_ACT_CMD";
	String EDIT_CONNECTION_ACT_CMD 		= "EDIT_CONNECTION_ACT_CMD";
	String CANCEL_CONNECTION_ACT_CMD 	= "CANCEL_CONNECTION_ACT_CMD";
	String CREATE_CONNECTION_ACT_CMD 	= "CREATE_CONNECTION_ACT_CMD";
	String TEST_CONNECTION_ACT_CMD 		= "TEST_CONNECTION_ACT_CMD";
	
	String DB_SYNC_ACT_CMD 				= "DB_SYNC_ACT_CMD";
	String EXECUITE_CURRENT_SQL_ACT_CMD	= "EXECUITE_CURRENT_SQL_ACT_CMD";
	String REFRESH_DATABASE_ACT_CMD 	= "REFRESH_DATABASE_ACT_CMD";
	String BACKUP_DATABSE_ACT_CMD 		= "BACKUP_DATABSE_ACT_CMD";
	
	String EXIT_APP_ACT_CMD 			= "EXIT_APP_ACT_CMD";
	
}
